spring:
  application:
    name: currency-exchange
  profiles:
    active: prod
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  slueth:
    sampler:
      probability: 1.0
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8082

eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true