server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: currency-exchange
#          uri: lb://currency-exchange
#          predicates:
#            - Path=/currency-exchange/**
#        - id: currency-conversion
#          uri: lb://currency-conversion
#          predicates:
#            - Path=/currency-conversion/**