server:
  port: ${PORT:8888}

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/bdprasad87/config-repo.git
          clone-on-start: true